# Generated by Django 3.1.4 on 2020-12-24 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=40, unique=True)),
                ('pw', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=5)),
                ('first_name', models.CharField(max_length=10)),
                ('nickname', models.CharField(max_length=40)),
                ('gender', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'account_info',
            },
        ),
        migrations.CreateModel(
            name='BoardList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=40, unique=True)),
                ('nickname', models.CharField(max_length=20)),
                ('board_num', models.IntegerField()),
                ('board_title', models.CharField(max_length=50)),
                ('board_contents', models.TextField()),
                ('board_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'boardlist',
            },
        ),
    ]
